### ISSUE TITLE
re-rendering infinitely

### ISSUE THREAD

**Issue by amzilayoub** [amzilayoub/ft_transcendence#39]
![image](https://user-images.githubusercontent.com/47505703/211113249-394fe5c0-160f-41cc-8a97-012a222af2b7.png)

![image](https://user-images.githubusercontent.com/47505703/211113213-19d40799-ef30-49f5-b9f4-0ce08945c024.png)

Hello @mbifenzi 
hadak l issue li kt gt lik abach matnsahch
mlli t fixih mark this issue as done and close it
thanks

**Comment by f0lio** [comment]
Fixed. But not a perfect fix; may change after sockets integration.
